"""
server/app.py — OpenEnv-compliant entry point for SRE-Incident-Gym.

This module wraps the existing SREIncidentGym environment in the
openenv_core.Environment base class and exposes a FastAPI `app`
created via openenv_core.create_app().

The validator requires:
  - A file at server/app.py
  - A [project.scripts] entry  sre-incident-gym-server = "server.app:run"
  - openenv-core>=0.2.0 listed in dependencies
  - A uv.lock file generated by `uv lock`
"""

from __future__ import annotations

import os
import random
from typing import Any, Literal, Optional

from openenv_core import Action, Environment, Observation, State, create_app
from pydantic import Field

# ---------------------------------------------------------------------------
# OpenEnv Action model
# ---------------------------------------------------------------------------

class SREAction(Action):
    """Single action for the SRE Incident Gym."""

    action_type: Literal[
        "check_logs",
        "restart_service",
        "scale_up",
        "apply_patch",
        "nop",
    ] = Field(..., description="Type of action to take")

    # Optional parameters used by some action types
    replicas: Optional[int] = Field(
        default=None, ge=1, le=10, description="Replicas for scale_up"
    )
    patch_id: Optional[str] = Field(
        default=None, description="Patch identifier for apply_patch"
    )

    # Override base model config to allow these extra-ish fields
    model_config = {"extra": "ignore", "validate_assignment": True}


# ---------------------------------------------------------------------------
# OpenEnv Observation model
# ---------------------------------------------------------------------------

class SREObservation(Observation):
    """Observation returned by the SRE Incident Gym at each step."""

    status_code: int = Field(..., ge=100, le=599, description="HTTP status code")
    cpu_load: float = Field(..., ge=0.0, le=100.0, description="CPU load %")
    memory_usage: float = Field(..., ge=0.0, le=100.0, description="Memory usage %")
    last_log_entry: str = Field(..., description="Latest log line")
    is_patched: bool = Field(..., description="Whether the security patch is applied")
    task_description: str = Field(default="", description="Human-readable task goal")

    model_config = {"extra": "ignore", "validate_assignment": True}


# ---------------------------------------------------------------------------
# OpenEnv State model
# ---------------------------------------------------------------------------

class SREState(State):
    """Full internal state (returned by /state endpoint)."""

    status_code: int = 200
    cpu_load: float = 0.0
    memory_usage: float = 0.0
    last_log_entry: str = ""
    is_patched: bool = False
    done: bool = False
    episode_reward: float = 0.0
    task_level: str = "EASY"

    model_config = {"extra": "allow", "validate_assignment": True}


# ---------------------------------------------------------------------------
# Task-level constants (mirrors environment.py without importing it)
# ---------------------------------------------------------------------------

_TASK_DESCS = {
    1: "Task 1 (Easy): restart_service to bring status 500 → 200.",
    2: "Task 2 (Medium): scale_up to reduce CPU from ~99% to ≤20%.",
    3: "Task 3 (Hard): scale_up (CPU ≤20%) AND apply_patch (security fix).",
    4: "Task 4 (Scheduled): nop — batch window active, do nothing.",
}


# ---------------------------------------------------------------------------
# OpenEnv Environment wrapper
# ---------------------------------------------------------------------------

class SREIncidentEnvironment(Environment[SREAction, SREObservation, SREState]):
    """
    OpenEnv-compliant wrapper around the SRE Incident Gym logic.

    The gym logic is reproduced inline here so that `server/app.py` is
    self-contained and the openenv_core validator can import it without
    requiring the rest of the project on sys.path.
    """

    SUPPORTS_CONCURRENT_SESSIONS = False

    # ------------------------------------------------------------------ #
    # Internal state                                                        #
    # ------------------------------------------------------------------ #

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._state: dict[str, Any] = {}
        self._task: int = 1
        self._step_count: int = 0
        self._max_steps: int = 15
        self._done: bool = False
        self._episode_reward: float = 0.0

    # ------------------------------------------------------------------ #
    # reset                                                                 #
    # ------------------------------------------------------------------ #

    def reset(
        self,
        seed: Optional[int] = None,
        episode_id: Optional[str] = None,
        task: int = 1,
        **kwargs: Any,
    ) -> SREObservation:
        if seed is not None:
            random.seed(seed)

        self._task = task
        self._step_count = 0
        self._done = False
        self._episode_reward = 0.0

        if task == 1:
            self._state = {
                "status_code": 500,
                "cpu_load": 45.0,
                "memory_usage": 60.0,
                "last_log_entry": "Internal Server Error. Inspecting stack trace… null pointer at handler.process()",
                "is_patched": True,
                "logs": ["Internal Server Error: null pointer in handler.process()"],
            }
        elif task == 2:
            self._state = {
                "status_code": 200,
                "cpu_load": random.uniform(70.0, 99.0),
                "memory_usage": random.uniform(50.0, 90.0),
                "last_log_entry": "Internal alert: high CPU utilization detected.",
                "is_patched": True,
                "logs": ["Alert: sustained high CPU utilization observed"],
            }
        elif task == 3:
            self._state = {
                "status_code": 200,
                "cpu_load": random.uniform(70.0, 99.0),
                "memory_usage": random.uniform(60.0, 90.0),
                "last_log_entry": "Critical: security scan flagged vulnerability and CPU is elevated.",
                "is_patched": False,
                "logs": ["Security scan: potential CVE-XXXX detected"],
            }
        elif task == 4:
            self._state = {
                "status_code": 200,
                "cpu_load": random.uniform(50.0, 70.0),
                "memory_usage": random.uniform(40.0, 60.0),
                "last_log_entry": "NOTICE: Scheduled batch window active; throughput spike expected.",
                "is_patched": True,
                "logs": ["Job scheduler: batch-run started"],
                "scheduled_batch": True,
            }
        else:
            raise ValueError(f"Invalid task: {task}. Must be 1–4.")

        return self._make_obs()

    # ------------------------------------------------------------------ #
    # step                                                                  #
    # ------------------------------------------------------------------ #

    def step(
        self,
        action: SREAction,
        timeout_s: Optional[float] = None,
        **kwargs: Any,
    ) -> SREObservation:
        if self._done:
            obs = self._make_obs()
            obs.done = True
            obs.reward = 0.0
            return obs

        self._step_count += 1
        step_penalty = -0.10
        reward = step_penalty
        FIX = 0.80
        WRONG = -0.40

        at = action.action_type

        if at == "check_logs":
            reward += 0.05
            logs = self._state.get("logs", [])
            self._state["last_log_entry"] = logs[0] if logs else "No new logs"

        elif at == "restart_service":
            if int(self._state.get("status_code", 200)) == 500:
                self._state["status_code"] = 200
                reward += FIX
            else:
                reward += WRONG

        elif at == "scale_up":
            cpu = float(self._state.get("cpu_load", 100.0))
            if cpu > 70.0:
                self._state["cpu_load"] = 20.0
                reward += FIX
            else:
                reward += WRONG

        elif at == "apply_patch":
            if self._task == 3 and not self._state.get("is_patched", False):
                self._state["is_patched"] = True
                reward += FIX
            else:
                reward += WRONG

        elif at == "nop":
            if self._task == 4:
                reward += FIX
                self._done = True
                self._episode_reward += reward
                obs = self._make_obs()
                obs.done = True
                obs.reward = min(1.0, max(-1.0, reward))
                return obs
            else:
                reward += -0.10

        # Scheduled task: any non-nop action ends episode with penalty
        if self._task == 4 and at != "nop":
            self._done = True
            self._episode_reward += -0.2
            obs = self._make_obs()
            obs.done = True
            obs.reward = -0.2
            return obs

        solved = self._check_solved()
        if solved or self._step_count >= self._max_steps:
            self._done = True
            if solved:
                self._state["last_log_entry"] = "TASK COMPLETE. System is healthy."

        final_reward = min(1.0, max(-1.0, reward))
        self._episode_reward += final_reward

        obs = self._make_obs()
        obs.done = self._done
        obs.reward = final_reward
        return obs

    # ------------------------------------------------------------------ #
    # state property                                                        #
    # ------------------------------------------------------------------ #

    @property
    def state(self) -> SREState:
        return SREState(
            status_code=self._state.get("status_code", 200),
            cpu_load=self._state.get("cpu_load", 0.0),
            memory_usage=self._state.get("memory_usage", 0.0),
            last_log_entry=self._state.get("last_log_entry", ""),
            is_patched=self._state.get("is_patched", False),
            done=self._done,
            episode_reward=self._episode_reward,
            task_level=["", "EASY", "MEDIUM", "HARD", "SCHEDULED"][self._task],
            step_count=self._step_count,
        )

    # ------------------------------------------------------------------ #
    # helpers                                                               #
    # ------------------------------------------------------------------ #

    def _check_solved(self) -> bool:
        if self._task == 1:
            return int(self._state.get("status_code", 0)) == 200
        elif self._task == 2:
            return float(self._state.get("cpu_load", 100.0)) <= 20.0
        elif self._task == 3:
            return bool(self._state.get("is_patched")) and float(self._state.get("cpu_load", 100.0)) <= 20.0
        return False

    def _make_obs(self) -> SREObservation:
        return SREObservation(
            status_code=int(self._state.get("status_code", 200)),
            cpu_load=float(self._state.get("cpu_load", 0.0)),
            memory_usage=float(self._state.get("memory_usage", 0.0)),
            last_log_entry=str(self._state.get("last_log_entry", "")),
            is_patched=bool(self._state.get("is_patched", False)),
            task_description=_TASK_DESCS.get(self._task, ""),
        )


# ---------------------------------------------------------------------------
# FastAPI app (required by the validator — must be named `app`)
# ---------------------------------------------------------------------------

app = create_app(
    env=SREIncidentEnvironment,
    action_cls=SREAction,
    observation_cls=SREObservation,
    env_name="SRE-Incident-Gym",
)


# ---------------------------------------------------------------------------
# CLI entry point  (used by [project.scripts])
# ---------------------------------------------------------------------------

def run() -> None:
    """Start the OpenEnv server. Called via `sre-incident-gym-server` CLI."""
    import uvicorn
    port = int(os.environ.get("PORT", 7860))
    uvicorn.run(
        "server.app:app",
        host="0.0.0.0",
        port=port,
        proxy_headers=True,
        forwarded_allow_ips="*",
    )


def main() -> None:
    """Main entry point — required by OpenEnv validator."""
    run()


if __name__ == "__main__":
    main()


# ---------------------------------------------------------------------------
# /api/* endpoints for dashboard.py
# These use a separate prefix to avoid conflicting with create_app() routes.
# dashboard.py must set API_BASE_URL = http://localhost:8000/api
# ---------------------------------------------------------------------------

from fastapi import Request
from fastapi.responses import JSONResponse

_dashboard_env: Optional[SREIncidentEnvironment] = None


@app.post("/api/reset")
async def api_reset(request: Request):
    global _dashboard_env
    body = await request.json()
    task = int(body.get("task", 1))
    if _dashboard_env is None:
        _dashboard_env = SREIncidentEnvironment()
    obs = _dashboard_env.reset(task=task)
    return {
        "observation": obs.model_dump(),
        "reward": None,
        "done": False,
        "task_description": _TASK_DESCS.get(_dashboard_env._task, ""),
    }


@app.post("/api/step")
async def api_step(request: Request):
    global _dashboard_env
    if _dashboard_env is None:
        _dashboard_env = SREIncidentEnvironment()
    body = await request.json()
    action_data = body.get("action", {})
    action = SREAction(**action_data)
    obs = _dashboard_env.step(action)
    return {
        "observation": obs.model_dump(),
        "reward": obs.reward,
        "done": obs.done,
    }


@app.get("/api/state")
async def api_state():
    global _dashboard_env
    if _dashboard_env is None:
        return JSONResponse({
            "status_code": 200, "cpu_load": 0.0, "memory_usage": 0.0,
            "last_log_entry": "Not yet reset — click Reset Environment.",
            "is_patched": False, "done": False,
            "episode_reward": 0.0, "step_count": 0, "task_level": "EASY",
        })
    return JSONResponse(_dashboard_env.state.model_dump())


@app.get("/api/health")
async def api_health():
    return {"status": "healthy", "version": "1.0.0"}


# ---------------------------------------------------------------------------
# Streamlit reverse proxy — serves dashboard at /dashboard on port 7860
# so both the OpenEnv validator (/reset, /step) and the UI are on one port.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Streamlit is served directly on port 8501 with baseUrlPath=/dashboard
# Users access it via HuggingFace's built-in port routing.
# We just add a redirect from / to the Streamlit URL for convenience.
# ---------------------------------------------------------------------------

from fastapi.responses import RedirectResponse as _Redirect

STREAMLIT_PORT = 8501

@app.get("/")
async def root():
    """Redirect root to Streamlit dashboard."""
    return _Redirect(url=f"http://localhost:{STREAMLIT_PORT}/dashboard")